name: godev

on:
  push:
    tags:
      - 'v*'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16
      -
        name: Call pkg.go.dev
        run: |
          go get github.com/${GITHUB_REPOSITORY}@${GITHUB_REF#refs/tags/}
        env:
          GO111MODULE: on
          GOPROXY: https://proxy.golang.org
